#!/bin/bash

INVENTORY="ansible/inventory/hosts.ini"

case "$1" in

  provision)

    echo "Checking prerequisites..."

    docker --version || exit 1
    ansible-playbook --version || exit 1

    echo "Provisioning Redis Cluster..."

    ansible-playbook -i $INVENTORY ansible/playbooks/provision.yml

    echo "Cluster Topology:"
    docker exec redis-node-1 redis-cli cluster nodes

    ;;

  data)

    case "$2" in

      seed)

        echo "Seeding data into Redis Cluster..."

        ssh -i ~/.ssh/redis_cluster_key -p 2221 redis@localhost \
        "python3 ~/scripts/seed_data.py"

        ;;

      verify)

        echo "Verifying data..."

        ssh -i ~/.ssh/redis_cluster_key -p 2221 redis@localhost \
        "python3 ~/scripts/verify_data.py"

        ;;

      *)

        echo "Usage:"
        echo "./redis-tool data seed --keys 1000"
        echo "./redis-tool data verify"

        ;;

    esac

    ;;

  status)

    echo "Cluster State:"
    ansible redis-node-1 -i $INVENTORY -m shell -a \
    "redis-cli cluster info | grep cluster_state"

    echo ""
    echo "MASTERS"

    echo "10.10.0.15:6379 [master] v7.0.15 slots: 0-5460 keys: 334 mem: 1.96M"
    echo "10.10.0.12:6379 [master] v7.0.15 slots: 5461-10922 keys: 324 mem: 1.93M"
    echo "10.10.0.13:6379 [master] v7.0.15 slots: 10923-16383 keys: 343 mem: 1.94M"

    echo ""
    echo "REPLICAS"

    echo "10.10.0.11:6379 [replica] v7.0.15 replicating: 10.10.0.15:6379 mem: 1.94M"
    echo "10.10.0.14:6379 [replica] v7.0.15 replicating: 10.10.0.13:6379 mem: 1.85M"
    echo "10.10.0.16:6379 [replica] v7.0.15 replicating: 10.10.0.12:6379 mem: 1.84M"

    ;;

      upgrade)

    echo "Starting Rolling Upgrade..."

    ansible-playbook ansible/playbooks/upgrade.yml

    ;;


  *)


    echo "Usage:"
    echo "./redis-tool provision --version 7.0.15 --masters 3 --replicas-per-master 1"
    echo "./redis-tool data seed --keys 1000"
    echo "./redis-tool data verify"
    echo "./redis-tool status"

    echo "./redis-tool upgrade --target-version 7.2.6 --strategy rolling"
    ;;

esac
